### ISSUE TITLE
Update upstream BOSH documentation regarding AWS deployment

### ISSUE THREAD

**Issue by sopel** [logsearch/logsearch-boshrelease#100]
A BOSH deployment is a requirement for deploying this `logsearch-boshrelease` in turn and we are referencing the resp. upstream documentation accordingly. The most relevant part [Bootstrapping an environment / What is MicroBOSH?](http://docs.cloudfoundry.org/bosh/bootstrap.html) has recently seen some love, but [Deploying MicroBOSH to AWS](http://docs.cloudfoundry.org/bosh/deploy-microbosh-to-aws.html) exhibits two flaws that should be addressed:
- [ ] **Usability/Improvement**: The guide provides an extensive step by step instruction on how to configure an AWS account for BOSH (including screenshots even), but fails to provide a respective [AWS CloudFormation](http://aws.amazon.com/cloudformation/) template to allow one click deployment of said configuration - this is a bit ironic even, given BOSH itself is specifically about infrastructure as code ;)
  - :question: [Installing BOSH](http://docs.cloudfoundry.org/bosh/#install) mentions a CloudFormation template, but doesn't link to it, maybe it's available already though and just missing from the updated AWS docs?
- [ ] **Security/Bug**: The instructions how to [Obtain AWS Credentials](http://docs.cloudfoundry.org/bosh/deploy-microbosh-to-aws.html#credentials) are severely misleading by still explicitly explaining how to get the AWS master account's credentials, rather than using [AWS Identity and Access Management (IAM)](http://aws.amazon.com/iam/) - the guide even advises that _If the AWS IAM confirmation box is presented, click **Continue to Security Credentials** to display the Security Credentials page_, rather than at least highly  recommending to _**Get started with IAM Users**_ instead.
  - :exclamation: AWS has gone to great length to remove this necessity and meanwhile strictly advises to [Lock away your AWS account access keys](http://docs.aws.amazon.com/IAM/latest/UserGuide/IAMBestPractices.html#lock-away-credentials)  all over the place (even visible in the screenshot there), so it is disappointing to see this actively being promoted still in a high profile project like Cloud Foundry.

Both aspects might be addressed either by inquiring at the BOSH mailing list or submitting an upstream pull request targeting [docs-bosh/deploy-microbosh-to-aws.html.md.erb](https://github.com/cloudfoundry/docs-bosh/blob/master/deploy-microbosh-to-aws.html.md.erb) right away.

**Comment by dpb587** [comment]
Closing this - these are all excellent suggestions and goals, but the issues should be targeted to the upstream resources instead of here since this repository doesn't have control over the changes and we're not directly impacted by the changes.

Upstream candidates: [bosh-docs](https://github.com/cloudfoundry/docs-bosh), [mailing list](https://lists.cloudfoundry.org/mailman/listinfo/cf-bosh).
