### ISSUE TITLE
how can I parse CloudFoundry Logs correctly?

### ISSUE THREAD

**Issue by michaelgrifalconi** [logsearch/logsearch-boshrelease#105]
I get logs like:

```
//////////////////////////////////////
{
  "_index": "logstash-2015.02.25",
  "_type": "syslog",
  "_id": "AUvBeTUFcI0w97WKMvxZ",
  "_score": null,
  "_source": {
    "@version": "1",
    "@timestamp": "2015-02-25T16:01:59.366+00:00",
    "host": "10.0.2.15",
    "@type": "syslog",
    "@message": "<14>2015-02-25T16:01:59.365253+00:00 10.244.0.6 vcap.nats [job=nats_z1 index=0]  {\"timestamp\":1424880119.364806,\"source\":\"NatsStreamForwarder\",\"log_level\":\"info\",\"message\":\"vcap.component.announce\",\"data\":{\"nats_message\": \"{\\\"type\\\":\\\"MetronAgent\\\",\\\"index\\\":0,\\\"host\\\":\\\"10.244.0.134:53421\\\",\\\"uuid\\\":\\\"0-\\\",\\\"credentials\\\":[\\\"pYcLm2zL-c8haF3oxm5vEmGktiCVersWcOqLA-Prb-LIgpblNgjCPDhz\\\",\\\"Gd01fmiuDvOGJwyNASoGXQlBQu32cQfKnL-mC_upkAewnrjDb8go961G\\\"]}\",\"reply_inbox\":null}}",
    "tags": [
      "_grokparsefailure-syslog_standard"
    ]
  },
  "sort": [
    1424880119366,
    1424880119366
  ]

//////////////////////////////////////
```

How can I get the ingestor parse correctly the logs?
Do I have to use this config? http://scottfrederick.cfapps.io/blog/2014/02/20/cloud-foundry-and-logstash

If yes, how can I set that config with the Bosh(lite) deploy? Where I have to write it? What I have to change in the manifest? 
I'm using the example deploy manifest https://github.com/logsearch/logsearch-boshrelease/blob/develop/examples

Thank you!
Michael

**Comment by mrdavidlaing** [comment]
@tyyko - take a look at the https://github.com/logsearch/logsearch-filters-cf repo - it has as set of filters that you need to parsing CF logs

**Comment by michaelgrifalconi** [comment]
Thanks for your link, now I know how to add filters, but that cf-filters are outdated and seems to dont work anymore..
By the way, I have another related question, if I would like to have something like that on the logstash config file:

input {
  # file {
  #  type => "syslog"
  # Wildcards work here :)
  #  path => [ "/var/log/syslog" ]
  # }
  tcp {
    add_field => {
      "cf_type" => "app"
    }
    port => 5000
    type => syslog
  }

to tag the logs into a specific port, how can I add it from the manifest?

Thank you again,
Michael

**Comment by mrdavidlaing** [comment]
@tyyko - We've just become aware of https://github.com/cloudfoundry-community/logsearch-boshworkspace, which might help.

Concerning editing an ingestor's logstash config; we don't currently support customising that (mainly for performance reasons, as its more difficult to scale ingestors than parsers).

Could you give us an idea of your requirements; and perhaps we can find a way to do the customisations you require without needing to edit the ingestor config.

/cc @dpb587

**Comment by michaelgrifalconi** [comment]
I'm not using boshworkspace, because on my bosh-lite VirtualBoxVM, I get:
 bosh prepare deployment
Unknown command: prepare deployment

Anyway, It looks like the same as following this guide http://www.cloudcredo.com/how-to-integrate-elasticsearch-logstash-and-kibana-elk-with-cloud-foundry/

My situation:

I get logs like:

```
{
  "_index": "logstash-2015.02.27",
  "_type": "syslog",
  "_id": "AUvKnFs3U3cCxXCSpD3T",
  "_score": null,
  "_source": {
    "@version": "1",
    "@timestamp": "2015-02-27T10:36:57.798+00:00",
    "host": "10.0.2.15",
    "@type": "syslog",
    "@message": "<14>2015-02-27T10:36:57.797676+00:00 10.244.0.6 vcap.nats [job=nats_z1 index=0]  {\"timestamp\":1425033417.797424,\"source\":\"NatsStreamForwarder\",\"log_level\":\"info\",\"message\":\"router.register\",\"data\":{\"nats_message\": \"{\\\"host\\\":\\\"10.244.0.138\\\",\\\"port\\\":9022,\\\"uris\\\":[\\\"api.10.244.0.34.xip.io\\\"],\\\"tags\\\":{\\\"component\\\":\\\"CloudController\\\"},\\\"index\\\":0,\\\"private_instance_id\\\":null}\",\"reply_inbox\":null}}",
    "tags": [
      "_grokparsefailure-syslog_standard"
    ]
  },
  "sort": [
    1425033417798,
    1425033417798
  ]
}
```

If I try to use the logsearch-filters-cf, (http://pastebin.com/e5805Kcb ) they don't work.

My source host is ALWAYS 10.0.2.15 (the eth0 in the vagrantBox, connected to the NAT on VirtualBox) and I cant figure out how to get the correct ip address, with wireshark i managed to know:

```
10.244.0.6(nats cf component MAC ADD) send log to -> 10.244.2.14 (10.244.0.5 vagrant MAC ADD)
~magic~
10.0.2.15 (vagrant eth0 MAC ADD) -> 10.244.2.14 (ingestor MAC ADD)
```

I could not do anything with IP tables to edit that and maintain the original source IP

Anyway, my target is to obtain a dashboard like that https://www.youtube.com/watch?v=OV4NwFQ0BA4 with log parsed correctly

My idea was to use this configuration https://gist.github.com/prysmakou/38ec5b7fda9845b2feca from this post https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/gqJGLtqGm-M

**Comment by mrdavidlaing** [comment]
@tyyko 2 questions.
1.  Which version of CF are you using?
2.  Are you looking to parse the logs of CF; or the logs of an application running on CF?  (or both?)

D

**Comment by michaelgrifalconi** [comment]
https://github.com/cloudfoundry/bosh-lite
https://github.com/cloudfoundry/bosh-lite/blob/master/docs/deploy-cf.md

This is what I did to deploy cf, i delpoyed the latest, v200

I would like to parse both CF components and apps, and keep them well separated, like with a tag

Thank you for your help!

**Comment by mrdavidlaing** [comment]
@tyyko Thanks.  We're quite a CF few versions behind you it seems.

I'm talking with the maintainers of https://github.com/cloudfoundry-community/logsearch-boshworkspace later today; I'll ask them how they're approaching this feed back to.

**Comment by mrdavidlaing** [comment]
@tyyko After speaking with the https://github.com/cloudfoundry-community/logsearch-boshworkspace maintainers, it sounds like they are looking to implement exactly what you are after.

The Logsearch team will be collaborating with cloudfoundry-community/logsearch-boshworkspace to help them to achieve what you are after.

I'm going to close this issue in favour of that project.
