### ISSUE TITLE
Failed to build logstash package

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#110]
I just tried to deploy the latest dev release to one of my clusters and it failed while building `logstash/ca11b0ef80b83955f6e82f964a0de14df683eb60`:

```
Error 450001: Action Failed get_task: Task fca81c14-7fe9-4c77-782c-8dbcab4e4034 result: Compiling package logstash: Running packaging script: Command exited with 1; Stdout: , Stderr: + set -u
+ mkdir /var/vcap/packages/logstash/logstash
+ tar -xzf logstash/logstash-1.5.0.rc2.tar.gz -C /var/vcap/packages/logstash/logstash --strip-components 1
+ JAVA_HOME=/var/vcap/packages/java8
+ PATH=/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/var/vcap/packages/java8/bin
+ /var/vcap/packages/logstash/logstash/bin/plugin install logstash-filter-alter logstash-filter-translate logstash-input-relp
Plugin logstash-filter-alter does not exist
Installation aborted
```

**Comment by dpb587** [comment]
Oops; ignore. I was using an internet-detached compilation instance and forgot this currently needs internet. Still hoping we can figure out a good way to change that packaging requirement by release.

**Comment by mrdavidlaing** [comment]
@dpb587 - [installing from local .gem files is scheduled for fixing in the logstash 1.5.0GA release](https://github.com/elastic/logstash/issues/2779); so we should be able to do remove this "internet" dependancy during compilation by v19 release.

**Comment by ph** [comment]
@mrdavidlaing I'll do more testing in a complete offline workflow, If the plugin doesn't have external dependencies it should work. (re the 1.5.0 GA)
