### ISSUE TITLE
ingestor_syslog (logstash 1.5) only listens on IPv6

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#111]
@simonjohansson says:

> I have a hard time to get logserach up and running. Well, it deploys, but out of the box on syslog_ingestor
> 
> ```
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      36/sshd         
> tcp        0      0 127.0.0.1:2822          0.0.0.0:*               LISTEN      63/monit        
> tcp6       0      0 :::33331                :::*                    LISTEN      34/bosh-agent   
> tcp6       0      0 :::22                   :::*                    LISTEN      36/sshd         
> tcp6       0      0 :::514                  :::*                    LISTEN      128/java        
> tcp6       0      0 :::2825                 :::*                    LISTEN      34/bosh-agent   
> udp6       0      0 :::514                  :::*                                128/java        
> ```
> 
> I.e logstash only listens on tcp6/udp6, did you ever have this issue?

**Comment by mrdavidlaing** [comment]
I've been able to replicate this issue on a new AWS deployment.

```
+-------------------+------------------------------------+------------------------------------------+
| Name              | Release(s)                         | Stemcell(s)                              |
+-------------------+------------------------------------+------------------------------------------+
| logsearch-aws-vpc | logsearch-for-cloudfoundry/0+dev.3 | bosh-aws-xen-ubuntu-trusty-go_agent/2778 |
|                   | logsearch/18+dev.64                |                                          |
|                   | route-registrar/1                  |                                          |
+-------------------+------------------------------------+------------------------------------------+
```

A hacky workaround is to [disable ipv6 on the ingestor instance](http://askubuntu.com/a/484487) and then `monit restart all`

**Comment by mrdavidlaing** [comment]
@dpb587 - Have you seen this before / have any idea how to "fix" it.

I think that the correct behaviour is that the ingestors should listen on BOTH IPv4 and IPv6

**Comment by simonjohansson** [comment]
Passing "-Djava.net.preferIPv4Stack=true" forces java to listen on tcp4.

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:514             0.0.0.0:*               LISTEN      645/java        
tcp        0      0 127.0.0.1:2822          0.0.0.0:*               LISTEN      64/monit        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      35/sshd         
tcp6       0      0 :::2825                 :::*                    LISTEN      34/bosh-agent   
tcp6       0      0 :::33331                :::*                    LISTEN      34/bosh-agent   
tcp6       0      0 :::22                   :::*                    LISTEN      35/sshd         
udp        0      0 0.0.0.0:514             0.0.0.0:*                           645/java        
```

But then we loose the ipv6 support.

**Comment by mrdavidlaing** [comment]
Interesting, in our meta.logsearch.io environment:

```
+---------------------------+----------------------------+----------------------------------------------+
| meta-logsearch-io         | logsearch-for-aws/0+dev.11 | bosh-aws-xen-ubuntu-trusty-go_agent-hvm/2798 |
|                           | logsearch-shipper/2        |                                              |
|                           | logsearch/18+dev.64        |                                              |
+---------------------------+----------------------------+----------------------------------------------+
```

we seem to also only be listening on IPv6, BUT, we are successfully accepting connections (from nxlog) 

```
 lsof -i | grep :5514
java      25151           root   16u  IPv6 1551372      0t0  TCP *:5514 (LISTEN)
java      25151           root   28u  IPv6 1551376      0t0  UDP *:5514 
java      25151           root   51u  IPv6 1551409      0t0  TCP 0.ingestor.vpc-public.meta-logsearch-io.microbosh:5514->0.log-parser.vpc-private.meta-logsearch-io.microbosh:56138 (ESTABLISHED)
java      25151           root   79u  IPv6 1551456      0t0  TCP 0.ingestor.vpc-public.meta-logsearch-io.microbosh:5514->0.queue.vpc-private.meta-logsearch-io.microbosh:50397 (ESTABLISHED)
```

I think nxlog is configured to connect to DNS name - `ingestor.meta.logsearch.io:5514`

Is it possible that we get some automagical DNS -> IPv6 translation? ( I really don't understand how IPv6 works)

**Comment by mrdavidlaing** [comment]
@simonjohansson, it occurs to me that we are seeing this issue with a "new" shipper - https://github.com/SpringerPE/firehose-to-syslog, and a "new" config - connecting to the ingestor_syslog on the same machine via `127.0.0.1:5514`

Could the failure to use IPv6 be related to either of those?

**Comment by dpb587** [comment]
The ingestors are taking advantage of "IPv4-mapped IPv6 addresses". Most OSes are enabled to support IPv4 connections over IPv6 (but not the other way around). For that reason, processes will typically bind to the IPv6 socket and lets the kernel take care of mapping IPv4 connections into the IPv6 space. In Linux you can confirm whether binds processes make will be IPv6 only with `net.ipv6.bindv6only` (i.e. connections to the port over IPv4 will _not_ work if this value is `1`):

```
$ sysctl net.ipv6.bindv6only
net.ipv6.bindv6only = 0
```

I don't think `tcp` vs `tcp6` is the issue here.

**Comment by mrdavidlaing** [comment]
@dpb587 - will attempting connect to 127.0.0.1:5514 work with "IPv4-mapped
IPv6 addresses"?

On Wednesday, April 1, 2015, Danny Berger notifications@github.com wrote:

> The ingestors are taking advantage of "IPv4-mapped IPv6 addresses". Most
> OSes are enabled to support IPv4 connections over IPv6 (but not the other
> way around). For that reason, processes will typically bind to the IPv6
> socket and lets the kernel take care of mapping IPv4 connections into the
> IPv6 space. In Linux you can confirm whether binds processes make will be
> IPv6 only with net.ipv6.bindv6only (i.e. connections to the port over
> IPv4 will _not_ work if this value is 1):
> 
> $ sysctl net.ipv6.bindv6only
> net.ipv6.bindv6only = 0
> 
> I don't think tcp vs tcp6 is the issue here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/logsearch/logsearch-boshrelease/issues/111#issuecomment-88478437
> .

## 

David Laing
logsearch.io - build your own open source cloud logging cluster
http://davidlaing.com

**Comment by dpb587** [comment]
Yes. Although note that in the originally pasted quote, it looks like `java` is listening on `514`, not `5514`.

**Comment by sopel** [comment]
Not sure I see the whole picture here (and tend to agree with @dpb587's explanation and assertion that `tcp` vs. `tcp6` isn't the issue), but it's worth noting that AWS basically still only support IPv4 (few exceptions for edge services like [ELB](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/using-elb-ipv6.html)), which means using IPv6 for AWS internal communication without an interim ELB (implying use of a public IP address and thus incurring the resp. bandwidth cost) is bound to fail. There are workarounds based on overlay networking, but presumably the implied complexities are ruling those out right away?!

**Comment by mrdavidlaing** [comment]
Leave this with me to try get a repro environment in place

**Comment by simonjohansson** [comment]
I should make it clear that when I did my initial findings I were in a VMWare environment, and not AWS.

**Comment by mrdavidlaing** [comment]
@dpb587, @simonjohansson 

I've just installed a new version of logsearch v19 on AWS; and have been able to replicate this bug. 

It seems to only surface when https://github.com/cloudfoundry-community/firehose-to-syslog attempts to connect to the `ingestor_syslog`.  

I have the ingestor_syslog and the ingestor_cloudfoundry-firehose running on the same node, with ingestor_cloudfoundry-firehose attempting to connect to ingestor_syslog on `127.0.0.1:5514`.

No logs make it from `ingestor_cloudfoundry-firehose` to  `ingestor_syslog`

A "fix" is to disable ipv6 by editing `/etc/sysctl.conf` on the ingestor_syslog node, and adding

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

to the end.

Then `sysctl -p` and finally restart affected services:

```
monit restart ingestor_syslog
monit restart ingestor_cloudfoundry-firehose
```

I propose that we try schedule some pairing time together to try figure this out together.

**Comment by simonjohansson** [comment]
@mrdavidlaing 
I cannot remember the exact details as it were some time ago I tried it out.

But I was not even putting firehose-to-syslog into the equation. I tried sending logs with the logger command diretly to logstash (to the default port given by the release)

Tcpdump showed my packages coming in to the box (over UDP, but not over TCP for obvious reasons :))

**Comment by shinji62** [comment]
firelog-to-syslog use tcp ipv6 or ipv4 to connect to the syslog http://golang.org/pkg/net/#Dial.

**Comment by mrdavidlaing** [comment]
I thought I'd seen this error [4 days ago](https://github.com/logsearch/logsearch-boshrelease/issues/111#issuecomment-100446538), but now that I sit down with @dpb587 I can't reproduce it.

I have the `ingestor_syslog` & `ingestor_cloudfoundry-firehose` jobs installed on the same AWS VM, and configured to talk via `127.0.0.1:5514`

Netstat shows me that `ingestor_syslog` is only listening on `tcp6/udp6`:

```
root@ec48ba44-5213-49c9-8db7-1be0947c923e:~# netstat -tul | grep 5514
tcp6       0      0 [::]:5514               [::]:*                  LISTEN     
udp6       0      0 [::]:5514               [::]:*                         
```

However, this doesn't appear to prevent `ingestor_cloudfoundry-firehose` from connecting over `tcp4`:

```
root@ec48ba44-5213-49c9-8db7-1be0947c923e:~# lsof -i | grep 5514
java      1619           root   39u  IPv6  14652      0t0  TCP *:5514 (LISTEN)
java      1619           root   46u  IPv6  14682      0t0  TCP localhost:5514->localhost:47730 (ESTABLISHED)
java      1619           root   53u  IPv6  14656      0t0  UDP *:5514 
java      1619           root   63u  IPv6  19693      0t0  TCP localhost:5514->localhost:47773 (ESTABLISHED)
firehose- 2177           vcap    4u  IPv4  13979      0t0  TCP localhost:47730->localhost:5514 (ESTABLISHED)
```

Finally, logs from the firehose are getting into logsearch - I can see them in Kibana

I'm also able to connect using telnet

```
root@ec48ba44-5213-49c9-8db7-1be0947c923e:~# telnet 127.0.0.1 5514
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Test message from telnet gugsughyt5
```

and see this message via Kibana (searching for the  `gugsughyt5` string)

@simonjohansson,

I'm unable to test messages to work with `logger`  using:

```
root@ec48ba44-5213-49c9-8db7-1be0947c923e:~# logger --server 127.0.0.1 --port 5514 "Test message from logger hy57gusg" 
```

Could you explain a bit more how you are testing using `logger` please

**Comment by simonjohansson** [comment]
@mrdavidlaing 
My bad, looking trough my history I see that I debugged with nc, and not logger

Fort TCP

```
echo "kehe TCP" | nc -w0 10.9.0.22 5514
```

For UDP

```
echo "kehe UDP" | nc -w0 -u 10.9.0.22 5514
```

**Comment by mrdavidlaing** [comment]
@simonjohansson,
Thanks for the further info.

I note that you were using nc to `10.9.0.22` - from which machine were you trying to connect?

Also, are you able to reproduce the issue with the latest [v19 release of `logsearch`](https://bosh.io/d/github.com/logsearch/logsearch-boshrelease?v=19) and [v2 release of `logsearch-for-cloudfoundry`](https://github.com/logsearch/logsearch-for-cloudfoundry/tree/master/logsearch-for-cloudfoundry-boshrelease)?

**Comment by simonjohansson** [comment]
@mrdavidlaing ah, this was to a machine that is long gone in our vSphere env.
I tried to nc from my local machine in that instance, nc to 127.0.0.1 on the machine itself did not work either.

Re trying with latest release I have not tried yet. Ill give it a go!

**Comment by mrdavidlaing** [comment]
@simonjohansson - Cool, thanks. 

Watch out [Mr Heisenbug](http://en.wikipedia.org/wiki/Heisenbug) - @simonjohansson and @mrdavidlaing are on your trail!

**Comment by simonjohansson** [comment]
@mrdavidlaing 

I did a quick test with bosh-lite.
https://asciinema.org/a/0tnglyy48m8pdl7enlczf75v5

Got a log trough, even though 

```
tcp6       0      0 :::5515                 :::*                    LISTEN      375/java
```

**Comment by simonjohansson** [comment]
```
A program bound to :: will be given traffic for any actual IPv6 address assigned to the system - it may also receive IPv4 traffic too in the form of IPv6-mapped IPv4 addresses
```

http://serverfault.com/questions/444554/what-does-mean-as-an-ip-address-bracket-colon-colon-bracket/452279#452279

So it seems I was just confused by the output of netstat due to lack of networking knowledge, and that this works due to ipv4 -> ipv6 translation.

:: -> listen on any interface, and the translation converts ipv4 to ipv6, and thus it works.

Edit:
Just like @dpb587 commented(but I somehow missed, would have saved me time on debugging :))
