### ISSUE TITLE
Template are totally out of date

### ISSUE THREAD

**Issue by shinji62** [logsearch/logsearch-boshrelease#125]
Hi,
Everyone seems your template are out of date .. not sure job "logsearch still exist".

Does anyone have a uptodate template ?

Thanks

**Comment by mrdavidlaing** [comment]
@shinji62, sorry - we should really remove the `templates/` folder, since we don't use it.

Take a look at https://github.com/logsearch/logsearch-boshrelease/tree/develop/examples
