### ISSUE TITLE
Improve kibana job's PID file

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#145]
The PID file for kibana is managed by the kibana process, but that PID file is not written until kibana has gone through its own startup steps. In particular, if a cluster is not fully started, kibana will block with `Elasticsearch is still initializing... Trying again in 2500 seconds` before it has written the PID file. This causes monit to think the process has not started yet and it will start multiple kibana processes whenever monit sees its not running.

Since kibana runs in foreground and is already `exec`'d by the control script, we should use the control script's PID instead of letting kibana write its own.

**Comment by yatzek-zz** [comment]
+1

**Comment by mrdavidlaing** [comment]
@yatzek Any chance of a PR for this from you?

**Comment by sapakl** [comment]
+1

**Comment by msaliminia** [comment]
+1
