### ISSUE TITLE
Kibana - where it is?

### ISSUE THREAD

**Issue by pako-grape** [logsearch/logsearch-boshrelease#162]
Hi
I' ve deployed logsearch-boshrelease v21 on aws and everything is ok - elasticsearch is collecting logs.
curl 10.10.7.10:9200/_cat/indices?v   shows that there are logs, but how to see these logs?
And main question how to access Kibana?
I will be really grateful if someone show me the way where to find Kibana...

**Comment by dpb587** [comment]
You'll find kibana 3 is installed at http://10.10.7.10:9200/_plugin/kibana/ as an elasticsearch plugin, or kibana 4 available on port 80 of whatever job you deployed the [`kibana`](https://github.com/logsearch/logsearch-boshrelease/tree/develop/jobs/kibana) template to.

**Comment by pako-grape** [comment]
Thank you very much for fast response:)
In deed there is Kibana 3, but maybe you know how to access it from outside? Not by private ip address...
Anyway thanks for your response again searching for it was very tiring:)

**Comment by dpb587** [comment]
If you need to access it by hostname or public IP, you'll need to configure it for that in your deployment manifest and DNS services - for that sort of thing you'll need to reference the BOSH documentation.

**Comment by pako-grape** [comment]
Ok, thanks for help.
