### ISSUE TITLE
Kibana 3.1.0 still present

### ISSUE THREAD

**Issue by petar-petrov-sap** [logsearch/logsearch-boshrelease#165]
Hi,

Is there a specific reason to install both Kibana 4.1.1 and the old 3.1.0 ?  The latter gets installed under job elasticsearch while the former is a dedicated job which was added in release v21.

If the old Kibana is not needed I can propose a git change to remove it.

Kind regards,
Petar Petrov

**Comment by dpb587** [comment]
Hi - thanks for the question. We still use Kibana 3 for some things (in addition to 4), so we don't have intentions of removing it in the near future. Preinstalling it as an elasticsearch plugin shouldn't be causing any issues, but let us know if it is for some reason.
