### ISSUE TITLE
Upgrade to Logstash 1.5.4

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#172]

**Comment by dpb587** [comment]
Still causing problems...

```
{
  :timestamp=>"2015-08-26T20:12:38.112000+0000",
  :message=>"SSL Error",
  :exception=>#<OpenSSL::SSL::SSLError: Client requested protocol SSLv3 not enabled or not supported>,
  :backtrace=>[
    "org/jruby/ext/openssl/SSLSocket.java:238:in `accept'",
    "/var/vcap/data/packages/logstash/57758aa5c6762137c71b863e167049f0cadd4a5e.1-1214d8e15e50c939d93dd5364c22f4393c2d9a8c/logstash/vendor/jruby/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:142:in `accept'",
    "/var/vcap/packages/logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:182:in `run_server'",
    "/var/vcap/packages/logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:170:in `run'",
    "/var/vcap/packages/logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:177:in `inputworker'",
    "/var/vcap/packages/logstash/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:171:in `start_input'"
  ],
  :level=>:error
}
```

I verified that `jdk.tls.disabledAlgorithms` was commented out in `/var/vcap/packages/java8/lib/security/java.security`. Additionally I tried uncommenting it with an empty value in case commented made it use the built-in defaults.

Searching more, I found the following [comment](https://github.com/elastic/logstash/issues/2328#issuecomment-128844578)...

> LS 1.5.3 explicitly removed support for SSLv3.

And was then able to find that implemented in [stronger_openssl_defaults.rb](https://github.com/elastic/logstash/blob/master/lib/logstash/patches/stronger_openssl_defaults.rb#L47-L50).

They originally discussed this in https://github.com/elastic/logstash/pull/3579 and was referenced in the Changelog as "Improved default security configuration for SSL".

This obviously means nxlog 2.8 from logsearch-shipper is incompatible which is how we're currently sending a bulk of our internal logs. Sad.

Decision time...

**Comment by cloudcredo-slack** [comment]
Most BOSH releases use the rsyslog baked into the stemcell for syslog
forwarding.

Does that support a compatible version of syslog?

Is switching from nxlog to rsyslog feasible?

**Comment by dpb587** [comment]
I originally used nxlog given our usage of it elsewhere and because it easily supported the dynamic fields/tagging of log messages which I think is much more complicated with rsyslog. It's not a switch that I'd be able to finish, test, and deploy by end of week, at least. I agree dropping nxlog for fewer dependencies would be convenient; it just hasn't been a necessity or priority.

You should remove your personal email from @cloudcredo-slack to ensure your replies are personally identified, and I suspect you don't actually want to use it to watch repos.

**Comment by mrdavidlaing** [comment]
@dpb587 - Thanks for the analysis. 

Given that switching to rsyslog isn't feasible given time constraints, what about upgrading to the binary version of nxlog 2.9?  The nxlog 2.9 binaries are available from http://nxlog.co/products/nxlog-community-edition/download.  

You could release a Ubuntu 14 only dev release of logsearchshipper this week whilst I poke NxLog again about releasing the 2.9 source.

**Comment by dpb587** [comment]
https://github.com/logsearch/logsearch-shipper-boshrelease/commit/4dd8e0350b8c07260d87d83061b7092fbafc962d has nxlog 2.9 for Ubuntu 14
