### ISSUE TITLE
test_e2e_errand fails when correct filters not deployed

### ISSUE THREAD

**Issue by yuanzhao** [logsearch/logsearch-boshrelease#173]
In the test_e2e_errand job,

```
curl -s '<%= p('test_e2e_errand.elasticsearch_hostport') %>/_all/sample-logs--repo-commits/_search?size=1024&pretty' > curl.out


echo '' ; echo '==> Validating results...'

#if ! grep '"total" : 30' curl.out > /dev/null 2>&1 ; then
#  fail 'Failed to capture expected number of messages'
#fi

#TESTLINE=$( grep '9d666a0da317777d35e763800ddfd8507cfb580c b056061ab74cc30ee2e6ea3e530f7262b2245228 2015-05-28 18:36:28 -0600 Danny Berger // Start experimenting with concourse' curl.out )
#echo "${TESTLINE}"

#if ! echo "${TESTLINE}" | grep '"commit":"9d666a0da317777d35e763800ddfd8507cfb580c"' > /dev/null 2>&1 ; then
#  fail 'Failed to capture commit field'
#elif ! echo "${TESTLINE}" | grep '"parents":\["b056061ab74cc30ee2e6ea3e530f7262b2245228"\]' > /dev/null 2>&1 ; then
#  fail 'Failed to capture parent field'
#fi

```

When I was trying to run this command "curl -s '<%= p('test_e2e_errand.elasticsearch_hostport') %>/_all/sample-logs--repo-commits/_search?size=1024&pretty' > curl.out", I got the following result, the total hits number is 0, but 30 is expected. 

```
{
  "took" : 19,
  "timed_out" : false,
  "_shards" : {
    "total" : 110,
    "successful" : 110,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

```

But if I ssh to the errand job instance, I can find the sample-logs/repo-commits/messages.log file.

**Comment by mrdavidlaing** [comment]
@yuanzhao, thanks for this bug report.  Could you let us know:
1.  Which version of logsearch-boshrelease you are using?
2.  What environment you are deploying to (e.g., BOSH-lite or AWS)

Thanks

**Comment by yuanzhao** [comment]
I am using the version 21 and the environment is aws

**Comment by mrdavidlaing** [comment]
@yuanzhao - we fixed some issues with the `test_e2e_errand` in v22 -  https://github.com/logsearch/logsearch-boshrelease/commit/4d58bb7fa0527faf264ff0e47deb68f459584852

Please could you try upgrade to that and check whether you see a similar issue

**Comment by dpb587** [comment]
Please make sure that you've included the correct logstash parser rules which extract fields and index type, otherwise you'll see the messages in a query to `/_all/_search`, but not in `/_all/sample-logs--repo-commits/_search` as the test expects. The `bosh-lite.yml` template configures the sample filters [here](https://github.com/logsearch/logsearch-boshrelease/blob/develop/templates/bosh-lite.yml#L182-L183).

**Comment by mrdavidlaing** [comment]
@dpb587 - Can we remove the need to include the additional `src/sample-logs/repo-commits/logstash-filters.conf` filters in the logsearch cluster being tested?  I suspect many people will fall into this gotcha.

Would it not be possible to change the search based on the `sourcehost` field added by the [`test_e2e_errand`](https://github.com/logsearch/logsearch-boshrelease/blob/develop/jobs/test_e2e_errand/templates/config/repo-commits.conf.erb#L22) ?

**Comment by dpb587** [comment]
It's supposed to be an end-to-end test, so I think it's appropriate to require filters to be configured. Otherwise it's not really testing all the stages and basic features of logsearch. We could add a more explicit note referencing filters to the testing section of the readme though.

**Comment by mrdavidlaing** [comment]
Closing since no longer relevant
