### ISSUE TITLE
Formalise process for creating new releases

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#18]
What should the branching process for creating a final release be?

We want to optimise for continuous delivery - ie, we want regular small changes to be deployed rather than batching them up into periodic releases.

We have third party consumers; who might not want quite so many releases; and definately want to know what changes are in each release.

**Comment by mrdavidlaing** [comment]
I'm wondering whether Git Flow might not be part of the answer.
1.  `feature-branch` gets new feature
2.  `feature-branch`-PR gets discussion (and possibly an automated build / deploy / test run)
3.  merge to `develop` branch - do your continuous deployment from here, creating and deploying your own `dev-release`s
4.  Weekly commit a new release to `develop`, create a PR to merge to `master` that contains the release notes/changelog (sort of like https://github.com/logsearch/logsearch-boshrelease/pull/16)
5.  Third parties consume from `master`

**Comment by mrdavidlaing** [comment]
@wdneto, @dpb587 - comments?

**Comment by dpb587** [comment]
What do other bosh repositories do for their processes?

**Comment by mrdavidlaing** [comment]
https://github.com/cloudfoundry/cf-release seems to be the "canonical" BOSH release

They have a `develop` branch; into which [PRs are merged](https://github.com/cloudfoundry/cf-release/pulls?direction=desc&page=1&sort=created&state=closed) 

Those PRs [have the uploaded blobs, but no release](https://github.com/cloudfoundry/cf-release/pull/366/files#diff-0)

I'm kinda confused as to what happens after that.

**Comment by aristotelesneto** [comment]
After I started messing with CF, I did enjoy learning about the Pivotal processes. The cf-release have the following branches which are involved in their release pipeline:

```
The pipeline interacts with the following ‘cf-release’ branches:
develop: Developers commit to this branch;
runtime-deployed: Continuous Integration system (CI) deploys this branch to Test environment (tabasco);
runtime-passed: CI runs Cloud Foundry Acceptance Tests (CATs) in Test environment and then promotes;
acceptance-deployed: CI deploys to Staging environment (a1) from this branch;
release-candidate: CI runs CATs in Staging environment and then promotes;
deployed-to-prod: Deploy to Production Environment (pws) from this branch;
master: Promoted (tagged) what was successfully deployed to Production;
```

They then leverage tags for when releases are created from the blobs / ready for world consumption, and promoted to master branch and individual commit progress tracked via http://git-pipeline.cfapps.io/

This may be way overkill, but seems to be a very nice foundation upon which to base any CI system on.

**Comment by mrdavidlaing** [comment]
For now, I propose we implement the following from the Pivotal processes:
- develop: Developers commit to this branch (via PR merges)
- release-candidate: Final releases go here.
- master: PRs containing the final releases from release-candidate that have been successfully deployed

As our continuous delivery pipeline matures, we can fill in the intermediate branches as we see fit.

**Comment by dpb587** [comment]
Is `release-candidate` necessary? When creating a release, wouldn't the dev branch off master, merge develop, create/commit release, push a new branch as a PR, and then let Jenkins QA against that PR?

**Comment by aristotelesneto** [comment]
How I understood it was:

A dev would branch off develop, and every commit merged in develop.
Tests would run against the develop branch, and promote whatever succeeds to release-candidate.
Releases created from release-candidate branch, and published to master.

**Comment by mrdavidlaing** [comment]
> push a new branch as a PR, and then let Jenkins QA against that PR?

I'm thinking that rather than creating a new branch, we just reuse `release-candidate` over and over (so multiple "release" PRs `release-candidate` -> `master`).  

I think it will make the Jenkins setup simpler:
- PR (new features) from `develop` -> run "unit" tests
- PR (new release) from `release-candidate` -> deploy to real clusters

> Tests would run against the develop branch, and promote whatever succeeds to release-candidate.

Initially I think the merge/promotion from `develop` to `release-candidate` will be manual.  But definately something that could be automated.

**Comment by dpb587** [comment]
Okay. You'll need to guide me through the process once for me to properly realize it.

**Comment by mrdavidlaing** [comment]
I'll run the process on https://github.com/logsearch/logsearch-boshrelease/pull/20 and see how it pans out.
- [x] PR #20 `issue-9` to `develop`; collaborate
- [x] merge PR #20 into `develop`
- [x] Create & deploy dev release to test cluster (meta.logsearch.io)
- [x] Create final release in `release-candidate`; deploy and test
- [x] PR #25 `release-candidate` -> `master` - add changelog notes
- [x] merge to `master`

**Comment by mrdavidlaing** [comment]
@dpb587, does the process documented above make a bit more sense?

I'm not completely convinced of the need for the `release-candidate` branch; but want to try another release (which is more automated) before making a final decision.
