### ISSUE TITLE
Kibana3 as a plugin

### ISSUE THREAD

**Issue by axelaris** [logsearch/logsearch-boshrelease#183]
Hi guys,
do we really need Kibana 3 as a ElasticSearch [plugin](https://github.com/logsearch/logsearch-boshrelease/blob/develop/packages/elasticsearch/packaging#L13-L17) since we have Kibana 4 there as a separate [package](https://github.com/logsearch/logsearch-boshrelease/blob/develop/packages/kibana/spec#L5-L6)?

**Comment by dpb587** [comment]
Depends on the installation, I guess. Personally I'm still using Kibana3 for many things, so would prefer it stick around. Is having it around causing problems in your deployments though? If so, I guess we could drop it and those needing it can list it as a remote plugin in their deployment properties. This question was also asked in #165, so maybe I'm missing something.

**Comment by axelaris** [comment]
Two Kibana's just brings us a bit of mess here.
It's not an urgent issue, but in long term perspective I believe one of them should be removed.

**Comment by mrdavidlaing** [comment]
Kibana 3 doesn't work with Elasticsearch 2.0 so when we merge https://github.com/logsearch/logsearch-boshrelease/pull/171 we'll remove Kibana 3
