### ISSUE TITLE
Failed parsing date from field

### ISSUE THREAD

**Issue by axelaris** [logsearch/logsearch-boshrelease#201]
This filter: https://github.com/logsearch/logsearch-boshrelease/blob/develop/src/logsearch-config/src/logstash-filters/if_it_looks_like_json.conf#L18-L23

causes a lot of parsing failures in the log:

```
{:timestamp=>"2016-02-04T13:41:55.753000+0000", :message=>"Failed parsing date from field", :field=>"[parsed_json_data][timestamp]", :value=>1454593315743606667, :exception=>"could not coerce Fixnum to class java.lang.String", :config_parsers=>"ISO8601", :config_locale=>"default=en_US", :level=>:warn}
{:timestamp=>"2016-02-04T13:41:55.756000+0000", :message=>"Failed parsing date from field", :field=>"[parsed_json_data][timestamp]", :value=>1454593315743629245, :exception=>"could not coerce Fixnum to class java.lang.String", :config_parsers=>"ISO8601", :config_locale=>"default=en_US", :level=>:warn}
{:timestamp=>"2016-02-04T13:41:55.759000+0000", :message=>"Failed parsing date from field", :field=>"[parsed_json_data][timestamp]", :value=>1454593315743643942, :exception=>"could not coerce Fixnum to class java.lang.String", :config_parsers=>"ISO8601", :config_locale=>"default=en_US", :level=>:warn}
```

I suggest to remove that block or, at least, replace `timestamp` with `time`, because `time` is in correct format.

**Comment by cromega** [comment]
We found that filter rather useful. Ideas for improving it (or PR to fix it) are more than welcome, though.

**Comment by kirederik** [comment]
As part of [release 201.0.12](https://github.com/logsearch/logsearch-boshrelease/releases/tag/v201.0.12) we made this filter optional (refer to the release notes for instructions).

Does this solve this issue? Can we close it?

Thanks

**Comment by axelaris** [comment]
Yes, thank you
