### ISSUE TITLE
Verify/Ensure enhanced networking is enabled on 14.04 HVM stemcells once available

### ISSUE THREAD

**Issue by sopel** [logsearch/logsearch-boshrelease#21]
[Enhanced Networking on Linux Instances in a VPC](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html) is a highly desirable side effect when using HVM instances in a VPC:

> With C3, R3, and I2 instances, you can enable enhanced networking capabilities. We support enhanced networking capabilities using single root I/O virtualization (SR-IOV). Enabling enhanced networking on your instance results in higher performance (packets per second), lower latency, and lower jitter.
> 
> To enable enhanced networking on your instance, you must ensure that its kernel has the required driver installed, and that you set the sriovNetSupport attribute for the instance.

As just mentioned in https://github.com/cityindex/logsearch/issues/359#issuecomment-42183628, the latter is the case for the _current Amazon Linux 2014.03 and Ubuntu LTS 14.04 HVM images_ and should ideally be available automatically once BOSH offers 14.04 based stemcells too, but given the custom image creation process, this should be explicitly verified and requested upstream if need be.

**Comment by sopel** [comment]
:information_source: see [Support for AWS Virtualization type 'hvm' ?](https://groups.google.com/a/cloudfoundry.org/d/msg/bosh-dev/p8r9TtlDIjg/oHg_3BFebdgJ) for a related discussion in the BOSH developers group.

**Comment by mrdavidlaing** [comment]
Pivotal have started [publishing Ubuntu 14.04 stemcells](http://bosh_artifacts.cfapps.io/file_collections?type=stemcells).

```
$ bosh public stemcells
+-------------------------------------------------------------+
| Name                                                        |
+-------------------------------------------------------------+
| bosh-stemcell-2524-aws-xen-ubuntu-trusty-go_agent.tgz       |
| light-bosh-stemcell-2524-aws-xen-ubuntu-trusty-go_agent.tgz |
+-------------------------------------------------------------+
```

However, these are not yet being promoted as "stable".

@sopel - do you know how we can check for:

> To enable enhanced networking on your instance, you must ensure that its kernel has the required driver installed

**Comment by sopel** [comment]
Finally, glad to see (HVM images are missing still though, which are a requirement here - we should hopefully be able to simply [do that ourselves](https://groups.google.com/a/cloudfoundry.org/d/msg/bosh-dev/p8r9TtlDIjg/SDtLKG3U0YwJ]) though, if need be).

[Testing Whether Enhanced Networking Is Enabled](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#test-enhanced-networking) describes the two steps to _verify that the driver is installed on your instance and that the sriovNetSupport attribute is set_.

```
$ sudo ethtool -i eth0
driver: ixgbevf
version: 2.11.3
firmware-version: N/A
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no

$ aws ec2 describe-instance-attribute --instance-id instance_id --attribute sriovNetSupport
    "SriovNetSupport": {
        "Value": "simple"
    },
```
- :information_source: obviously only the former can be verified with the PV images at hand, but that would allow us to proceed with manual HVM image generation already
- :exclamation: the documentation mentions [describe-image-attribute](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-image-attribute.html) to _check whether an AMI already has the enhanced networking attribute set_, however, this doesn't seem to work for images owned by someone else (likely due to security relevant info being included in those attributes)
- :white_check_mark: however, [describe-instance-attribute](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-attribute.html) works as documented for that purpose once an instance has been started from an AMI (that's how I verified  the Ubuntu 14.04 HVM image having that attribute set now, because 12.04 HVM hasn't)

**Comment by mrdavidlaing** [comment]
On an instance started from stemcell: `bosh-stemcell-2524-aws-xen-ubuntu-trusty-go_agent.tgz` - `Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)`

```
# sudo ethtool -i eth0
driver: vif
version: 
firmware-version: 
bus-info: vif-0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

I think this means that it doesn't have the required driver

**Comment by dpb587** [comment]
I ran this against `elasticsearch_eu-west-1c/0` which is running as `r3.2xlarge` from `bosh-aws-xen-ubuntu-trusty-go_agent-hvm@2549`.

```
local$ aws ec2 describe-instance-attribute --instance-id i-5bef4b19 --attribute sriovNetSupport | jq -c -r '.SriovNetSupport'
{"Value":"simple"}
i-5bef4b19$ sudo apt-get install -y ethtool && sudo ethtool -i eth0
driver: ixgbevf
version: 2.11.3-k
firmware-version: 
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

@sopel, can you verify that these results confirm enhanced networking usage? Then I think this issue can be closed?

**Comment by sopel** [comment]
Excellent, thanks for integrating this :)

**Comment by rchekaluk** [comment]
I'm curious if anyone on this thread has succeeded in upgrading Ubuntu Trusty ixgbevf from version 2.11.3-k to the ~~[recommended](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html)~~ most recent version 2.15.3.

In attempting to [build ixgbevf from source](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enhanced-networking-ubuntu), I've encountered [this error](http://sourceforge.net/p/e1000/mailman/message/32788809/#msg32789086), even after upgrading the kernel to  3.13.0-35-generic.

**Comment by mrdavidlaing** [comment]
@rchekaluk - I'm afraid we haven't tried, so can't comment
