### ISSUE TITLE
cluster_monitor?

### ISSUE THREAD

**Issue by tomsherrod** [logsearch/logsearch-boshrelease#218]
Is cluster_monitor a new addition?
When generating the yml, cluster_monitor is missing for the openstack example.
I added it in the stub and deploy.
cluster_monitor fails to run after update.
Before debugging further, is there a release or tag that should be used for stable?
I went with v201.0.9 tag/checkout.

Many thanks.

**Comment by tomsherrod** [comment]
The nats_to_syslog job is setting nats-uri: nats://nats:nats-password@10.0.0.6:4222
10.0.0.6 is NOT part of the mainfest.

What job/instance would be considered the nats host?

Thanks,
Tom

**Comment by cromega** [comment]
@tomsherrod: yes, the cluster monitor is a relatively new addition. It is a VM that gathers metrics from the other logsearch VMs.

The default target of the nats_to_syslog job is 10.0.0.6 which is the default IP of the BOSH director. Running a NATS client subscribing to specific messages is how the cluster_monitor gathers its data. In your deployment point it to whatever the IP of the BOSH director is.

For a stable commit pick a tag that corresponds to a release. v201.0.9 is the latest as of now.

**Comment by tomsherrod** [comment]
That worked.

**Comment by tomsherrod** [comment]
Worked after pointing to correct director.
