### ISSUE TITLE
openstack stub, no haproxy?

### ISSUE THREAD

**Issue by tomsherrod** [logsearch/logsearch-boshrelease#219]
The openstack example stub doesn't include an haproxy.
Is this intentional? If so, the only floating/external ip is for the ingestor. How do you reach kibana?

Thanks.

**Comment by cromega** [comment]
@tomsherrod: The openstack templates are not up-to-date with latest changes as we don't actually run the release on it nowadays. It should include the haproxy.

If you happen to use the release on openstack feel free add some missing bits and send a PR. Thanks

**Comment by tomsherrod** [comment]
I'm working my way to that point. I hesitate to do a PR when I have yet to get it working.
I did get an haproxy up. I find something getting pushed in and resulting with fail/syslog_standard/_grokparsefailure, with no other configuration.
Pointers in debugging?

**Comment by cromega** [comment]
@tomsherrod: Umm, that's one of those things...

We also noticed that even without any components actually configured to send logs to the ingestor there are some hits in kibana which don't look like normal logs and they can't be parsed properly. We have yet to get to the bottom of if.

To test your configuration just point your deployments at the haproxy ingestor port and confirm that it works.

**Comment by tomsherrod** [comment]
Got it working.
