### ISSUE TITLE
Curator template

### ISSUE THREAD

**Issue by t2sa** [logsearch/logsearch-boshrelease#238]
**File:** templates/logsearch-jobs.yml

**Line 76:**

```
Current: 
elasticsearch_host: 127.0.0.1
Proposed: 
elasticsearch:
  host: 127.0.0.1
```

**Line 226:**

```
Current: 
elasticsearch_host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
Proposed: 
elasticsearch:
  host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
```

**Comment by cromega** [comment]
@t2sa: Yeah, we know about a few inconsistencies in how we configure some jobs, we know a few messy corners, we may as well start cleaning up with this one. Thanks for pointing it out!

**Comment by cromega** [comment]
@t2sa: are you sure you're looking at the latest version of logsearch-jobs.yml? We fixed [line 76](https://github.com/logsearch/logsearch-boshrelease/commit/92bacc598bfeb7fa191d8c613706ff994b723872)
 but couldn't find any other occurences of elasticsearch_host

**Comment by t2sa** [comment]
@cromega I might have looked at an older version of logsearch-jobs.yml. Thank you for fixing line 76. Noticed you took care of the port too, thank you.
