### ISSUE TITLE
Cannot create bosh release

### ISSUE THREAD

**Issue by egurnov** [logsearch/logsearch-boshrelease#256]
Hi everyone, 

when I try to build a bosh release from v203.0.0, I keep getting HTTP 403 for haproxy package:
```
Building haproxy...
  Using final version '231e1fbdfee34eefddc2ce45eccd74272c68c98b'
  Downloading from blobstore (id=00c1d468-1ad6-43e1-be65-d9b8404271b4)...
Blobstore error: Could not fetch object, 403/
```

How I got here:
```
git clone git@github.com:logsearch/logsearch-boshrelease.git
cd logsearch-boshrelease
git co v203.0.0
git submodule update --init --recursive
bosh create release
```

How do I fix this?

Regards,
Alexander Egurnov

**Comment by supp429** [comment]
+1 we have been experiencing the same error.

**Comment by bonzofenix** [comment]
My guess is that some blobs where not migrated property to the new blobstore. The other one does not seem to be public anymore. https://github.com/logsearch/logsearch-boshrelease/commit/adc57069c6b71f79132e85559bbc22fe36db642d#diff-5ccaee0392b76270e95d5a267c032e14R5
