### ISSUE TITLE
Saving Kibana dashboard throws No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#3]
[Elasticsearch%20Requests](http://kibana-meta-logsearch-io.monitor-cloud.cityindextest5.co.uk/index.html#/dashboard/elasticsearch/Elasticsearch%20Requests) > Save dashboard, JS console shows:

```
XMLHttpRequest cannot load http://api.meta.logsearch.io/kibana-int/dashboard/Elasticsearch%20Requests. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://kibana-meta-logsearch-io.monitor-cloud.cityindextest5.co.uk' is 
therefore not allowed access. 
```

**Comment by dpb587** [comment]
@mrdavidlaing, are you sure the running cluster has a clean nginx config? This is working fine for me on the local release-4 bosh-lite.

**Comment by mrdavidlaing** [comment]
no reason not to delete and recreate...

**Comment by mrdavidlaing** [comment]
```
Below is the list of resolutions you've provided
Please make sure everything is fine and confirm your changes

  1. api/0 (i-46362406) is not responding
     Recreate VM using last known apply spec

Apply resolutions? (type 'yes' to continue): yes
Applying resolutions...

Director task 2785
  Started applying problem resolutions > unresponsive_agent 383: Recreate VM using last known apply spec. Done (00:01:48)

Task 2785 done

Started     2014-04-08 15:38:01 UTC
Finished            2014-04-08 15:39:49 UTC
Duration    00:01:48
Cloudcheck is finished
```

**Comment by mrdavidlaing** [comment]
Bummer; error still happening...

**Comment by dpb587** [comment]
@mrdavidlaing, `sudo chmod o+x /var/vcap/sys` seems to fix the issue (see [diagnosis blog post](http://labs.cityindex.com/labs-team/2014/04/08/chrome-and-cors-error-deception/)). Do you have any ideas why it's different between the meta cluster and the bosh-lite cluster I run locally?

**Comment by mrdavidlaing** [comment]
I'm going to guess because bosh-lite uses a virtualised container filesystem; and it isn't applying permissions in the same way as a real filesystem.

The thing that jumps out for me is that the nginx worker processes are running as `nobody`, which isn't part of the `vcap` group; and thus probably shouldn't have access to `/var/vcap/sys`

```
PID USER      PGRP PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
915 root       914  10 -10  4160   568   476 S  0.0  0.0  0:00.00 /bin/sh /var/vcap/jobs/api/bin/monit_debugger nginx_ctl /var/vcap/jobs/api/bin/nginx_ctl star
  919 root       914  10 -10 28184  2684  1964 S  0.0  0.2  0:00.02 nginx: master process /var/vcap/packages/nginx/sbin/nginx -c /var/vcap/jobs/api/config/nginx.
  940 nobody     914  10 -10 31660  5048   892 S  0.0  0.3  0:01.78 nginx: worker process
```

I think the "fix" is going to be to configure nginx to run its worker processes as user `vcap`

**Comment by dpb587** [comment]
Looks like this is my fault - you had `user vcap vcap` in your [initial commit](https://github.com/logsearch/logsearch-boshrelease/blob/be4b5478f3b99bfb6577ecb79b54d016d05fb71c/jobs/api/templates/config/nginx.conf.erb#L1), but I lost that line when cleaning up the config and bringing it up to date from the other repo.

**Comment by mrdavidlaing** [comment]
Heh, nice catch :)

**Comment by mrdavidlaing** [comment]
@dpb587 - has this been incorporated into a BOSH release?

**Comment by dpb587** [comment]
No, I thought we said to commit the changes on a release-5 branch and we'd commit the release when we were ready.

**Comment by mrdavidlaing** [comment]
I think we've miscommunicated.  Why don't you proceed with what you have in mind; and then we can discuss the process.

I think we should have _lots_ of small releases; I don't see any reason to wait and bundle up multiple changes into a single release.

**Comment by dpb587** [comment]
Merged and release created.
