### ISSUE TITLE
Allow overriding the number of workers logstash starts

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#31]
By default, it's using one worker per CPU. I think it's a good default, but, for better throughput we may want to run it a bit hotter with more workers.

I think we should add a `logstash_parser.workers` property defaulting to `auto` (dynamically derived from CPU), but allow an integer to be explicitly specified.

**Comment by mrdavidlaing** [comment]
@dpb587 - Can you envisage a situation where you would not want to "run it a bit hotter"

I think that reducing complexity by avoiding adding another knob to twiddle might be a good idea; so if we can get away with it I'd just increase the number of workers and not add a setting

**Comment by dpb587** [comment]
No, but I don't think it's something we can safely hardcode. Our filters are relatively simple, so it's easy to double the workers without noticeably impacting our performance. But, other users may have more complex lookups or external calls which add load that we can't account for in a simple way. I think it'd be better to have a setting for it.

Also, I disagree with "reducing complexity by ... not adding a setting". Adding the setting and requiring users to know upfront what value they should use adds complexity, but having a sane default like our current 1 worker per CPU avoids that. I believe by adding the setting we'd make this BOSH release more accessible and cost-efficient to a wider range of users, including ourselves.

**Comment by mrdavidlaing** [comment]
> Our filters are relatively simple, so it's easy to double the workers without noticeably impacting our performance

I think this is the clincher as to why this needs to be a setting you can change / deployment - its dependant on the complexity of the filters used.

So, :+1: for adding it, along with the sane default

**Comment by dpb587** [comment]
This landed in release 10.
