### ISSUE TITLE
Allow configuring log_parser's idle_flush_time

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#32]
By logstash's default it's 1 second, but to make things easier for performance tweaking, it'd be nice if we allowed it to be changed.

**Comment by mrdavidlaing** [comment]
Can you explain how / why you would want to change it during performance tweaking?

**Comment by dpb587** [comment]
Depending on instance types, disk types, and network topologies users are configuring, it may be more performant to send larger batches of events per connection rather than smaller batches and frequent connections.

**Comment by mrdavidlaing** [comment]
Since this setting is dependant on `instance types, disk types, and network topologies`; which are definately deployment config concerns, then I agree that it should be a spec setting.

**Comment by dpb587** [comment]
This landed in release 10.
