### ISSUE TITLE
Better handling of disk space errors

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#36]
Running out of persistent disk space causes a cascading error
1.  ES indicies are stored on the BOSH persistent volume; and we currently don't have a good way of monitoring this, or automatically purging old data.
2.  ES will stop indexing new data, causing the queue to start backing up.
3.  If the BOSH persistent volume fills up, ES starts logging errors like below, which pretty quickly fill up the BOSH ephemeral volume.  Recover is a manual process of SSHing into the instance and `sudo rm -f /var/vcap/sys/log/elasticsearch/elasticsearch.std*`:

```
[2014-05-31 06:26:08,228][WARN ][indices.cluster          ] [Tuc] [logstash-2014.05.20][0] failed to start shard
org.elasticsearch.indices.recovery.RecoveryFailedException: [logstash-2014.05.20][0]: 
...snip...
Caused by: java.io.FileNotFoundException: /var/vcap/store/elasticsearch/live-logsearch/nodes/0/indices/logstash-2014.05.20/0/index/recovery.1401517566653._11ge.nvd (No space left on device)
```

I think we should start with a better disk space usage alerting system; followed by some combination of documentation on how to react and some automated tooling.

**Comment by aristotelesneto** [comment]
https://github.com/nttlabs/bosh-scaler might be of interest

**Comment by mrdavidlaing** [comment]
@wdneto - I've been following https://github.com/nttlabs/bosh-scaler with interest; but don't understand how it would help with disk full monitoring / handling.

Could you explain?

**Comment by aristotelesneto** [comment]
Sorry, I'm thinking too much CF. bosh-scaler picks up things via the /varz endpoint - meaning it wouldn't be applicable to ES servers. 

Perhaps we could add a /varz style endpoint to logsearch servers, and leverage some of the existing logic in bosh-scaler.

**Comment by dpb587** [comment]
Until a better solution comes along we've been using a bot to periodically check our disk stats (as reported by [logsearch-shipper](https://github.com/logsearch/logsearch-shipper-boshrelease)) and alert us if they pass generic thresholds.

As far as this issue goes, I'm closing it. It's an operational issue - generic among all deployments, not just elasticsearch/logsearch - and it's not something we can independently solve with this logsearch release. Different sort of project.

**Comment by dpb587** [comment]
Also, we do utilize [curator](https://github.com/elastic/curator), scheduled externally from the deployment, to keep a fairly consistent amount of data within our typical thresholds.
