### ISSUE TITLE
Enable direct document access in nginx proxy

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#39]
Primarily for debugging, but it'd be convenient to allow direct access to documents by ID. The regex should probably just allow all `GET`s to `/{index}/{type}/[^_].+`.

For example... this document is being parsed incorrectly...

```
http://api.meta.logsearch.io/logstash-2014.06.05/relp_cf/YTLKANrZQeqSY2JDFEdaTw?pretty
```

**Comment by mrdavidlaing** [comment]
Seems like a good idea to me

**Comment by dpb587** [comment]
I realized generated IDs are allowed to use underscores as the first character which makes it difficult to avoid internal calls in proxy rules (not that `GET` internal calls should be dangerous, but least access has been our convention so far). Given this was only a debugging change and there are other ways to easily lookup a document (e.g. kibana search for `_id:YTLKANrZQ...`, `/{index}/{type}/_search?q=_id:YTLKAnrZQ`), it's just easier to avoid hacking up the nginx proxy rules. Closing...

**Comment by mrdavidlaing** [comment]
Probably the correct call at this stage.

For reference: http://stackoverflow.com/a/19898676/13238

> Auto-generated ids are random base64-encoded UUIDs. The base64 algorithm is used in URL-safe mode hence - and _ characters might be present in ids.
