### ISSUE TITLE
Update to bosh_cli 1.2619.0 (was 1.2291.0)

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#49]
You will need to upgrade your BOSH director to handle the new BOSH versioning scheme

```
You are using CLI > 1.2579.0 with a director that doesn't support the new version format you are using. Upgrade your director to match the version of your CLI or downgrade your CLI to 1.2579.0 to avoid versioning mismatch issues.
```

**Comment by dpb587** [comment]
I actually upgraded locally during my efforts of debugging the blob issues and uploaded a couple releases using it. I'm curious... were you required to upgrade locally to deploy after me? It said it was downgrading the release to the older version, so I didn't expect it to be an issue.
