### ISSUE TITLE
 Package `elasticsearch' has a glob that resolves to an empty file list: elasticsearch/elasticsearch-1.2.1.tar.gz

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#50]
```
$ bosh create release --force
Syncing blobs...
collectd/collectd-5.4.1.tar.gz downloaded                                       
collectd/collectd-elasticsearch-logstash.... downloaded                         
collectd/collectd-elasticsearch.py downloaded                                   
collectd/collectd-librato.py downloaded                                         
collectd/collectd-redis-logstash.py downloaded                                  
collectd/collectd-redis.py downloaded                                           
elasticsearch/cloud-aws-1.14.0.tar.gz downloaded                                
elasticsearch/elasticsearch-0.90.5.tar.gz... downloaded                         
elasticsearch/elasticsearch-1.0.1.tar.gz downloaded                             
elasticsearch/elasticsearch-HQ-1.1.0.tar.... downloaded                         
elasticsearch/jetty-0.90.0.tar.gz downloaded                                    
elasticsearch/jetty-1.0.1-beta.zip downloaded                                   
elasticsearch/kibana-3.0.1.tar.gz downloaded                                    
elasticsearch/marvel-1.1.0.zip downloaded                                       
java7/openjdk-1.7.0_51.tar.gz downloaded                                        
logstash/logsearch-filters-common--21e1a3... downloaded                         
logstash/logsearch-filters-common--a787b4... downloaded                         
logstash/logstash-1.3.0.jar downloaded                                          
logstash/logstash-forwarder-1.4.0.rc1 downloaded                                
logstash-filters-common/logstash-filters-... downloaded                         
nginx/nginx-1.4.2.tar.gz downloaded                                             
nginx/nginx-1.4.7.tar.gz downloaded                                             
nginx/pcre-8.33.tar.gz downloaded                                               
python/Python-2.7.6.tgz downloaded                                              
redis/redis-2.8.4.tar.gz downloaded                                             

Building DEV release
---------------------------------

Building packages
-----------------
Building collectd...
  Final version:   FOUND LOCAL

Building elasticsearch...
  Final version: Package `elasticsearch' has a glob that resolves to an empty file list: elasticsearch/elasticsearch-1.2.1.tar.gz
```

**Comment by dpb587** [comment]
Run the commands in the Upstream Blobs wiki page; I haven't uploaded them
to S3.

On Fri, Jun 27, 2014 at 10:14 AM, David Laing notifications@github.com
wrote:

> $ bosh create release --force
> Syncing blobs...
> collectd/collectd-5.4.1.tar.gz downloaded
> collectd/collectd-elasticsearch-logstash.... downloaded
> collectd/collectd-elasticsearch.py downloaded
> collectd/collectd-librato.py downloaded
> collectd/collectd-redis-logstash.py downloaded
> collectd/collectd-redis.py downloaded
> elasticsearch/cloud-aws-1.14.0.tar.gz downloaded
> elasticsearch/elasticsearch-0.90.5.tar.gz... downloaded
> elasticsearch/elasticsearch-1.0.1.tar.gz downloaded
> elasticsearch/elasticsearch-HQ-1.1.0.tar.... downloaded
> elasticsearch/jetty-0.90.0.tar.gz downloaded
> elasticsearch/jetty-1.0.1-beta.zip downloaded
> elasticsearch/kibana-3.0.1.tar.gz downloaded
> elasticsearch/marvel-1.1.0.zip downloaded
> java7/openjdk-1.7.0_51.tar.gz downloaded
> logstash/logsearch-filters-common--21e1a3... downloaded
> logstash/logsearch-filters-common--a787b4... downloaded
> logstash/logstash-1.3.0.jar downloaded
> logstash/logstash-forwarder-1.4.0.rc1 downloaded
> logstash-filters-common/logstash-filters-... downloaded
> nginx/nginx-1.4.2.tar.gz downloaded
> nginx/nginx-1.4.7.tar.gz downloaded
> nginx/pcre-8.33.tar.gz downloaded
> python/Python-2.7.6.tgz downloaded
> redis/redis-2.8.4.tar.gz downloaded
> 
> ## Building DEV release
> 
> ## Building packages
> 
> Building collectd...
>   Final version:   FOUND LOCAL
> 
> Building elasticsearch...
>   Final version: Package `elasticsearch' has a glob that resolves to an empty file list: elasticsearch/elasticsearch-1.2.1.tar.gz
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/logsearch/logsearch-boshrelease/issues/50.

## 

Danny Berger
http://dpb587.me

**Comment by mrdavidlaing** [comment]
@dpb587 Will do; and I'll upload them to S3
