### ISSUE TITLE
Setting logstash_ingestor.debug throws Unknown setting 'debug' for stdout"

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#53]
Since logstash 1.4, stdout no longer support the `debug` field.

(jobs/ingestor_syslog/templates/config/syslog_to_redis.conf.erb)[https://github.com/logsearch/logsearch-boshrelease/blob/master/jobs/ingestor_syslog/templates/config/syslog_to_redis.conf.erb#L15-L17] which reads:

```
<% if p("logstash_ingestor.debug") %>
    stdout { debug => true codec => "json"}
    <% end %>
```

Should read

```
<% if p("logstash_ingestor.debug") %>
    stdout { codec => "json"}
    <% end %>
```

**Comment by dpb587** [comment]
I fixed the outputs when I upgraded logstash (see `develop` branch), but somehow missed the `relp` input one (committed fix above).
