### ISSUE TITLE
Drop idea of dedicated "master" vs "develop" branch

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#57]
We've shifted away from the original release proposal which started us having a separate `develop` and `master` branch. Now that we're actively using git tags and fast-forward merging `master`, I don't think it makes sense to maintain independent branches.

I'd like to get rid of the separate branches in favor of just using `master`.

If approved, locally you should remove your existing `master` branch (if used), rename your `develop` branch (for mental sanity), and then retarget your `develop` branch to the `master` one:

```
git branch -d master
git branch -m develop master
git branch master --set-upstream-to origin/master
```

**Comment by dpb587** [comment]
@mrdavidlaing, are you okay with this?

**Comment by aristotelesneto** [comment]
It may not be my place to say this, particularly since you're responsible for the majority of the commits, but I think it may seem redundant because we are creating releases with each group of commits, and the number of commits isn't that large. Not only that but we're currently manually merging develop back into master (as opposed to CI).

Having said that, I'd still maintain that it's good practice to do general development on a different branch.

**Comment by dpb587** [comment]
We discussed this a bit more in [Flowdock](https://www.flowdock.com/app/cityindexlabs/logsearch/messages/2240347), but we didn't come to a definitive conclusion so @mrdavidlaing says we observe the following for the time being...
1. Delete the master branch
2. Commit to the develop branch (small directly, larger via PR)
3. Use tags to denote stable bits
4. Adding more branches as our CD process grows and requires them

**Comment by dpb587** [comment]
In terms of when to denote stable bits, @mrdavidlaing suggests...

> Say we have milestone N with a bunch of issues assigned to it.  Up until the point that all the issues are closed, we’re definitely at release (N-1).dev+Y
> 
> After all the issues are closed, and the final (N-1).dev+Y release has been deployed to our internal clusters, nothing has gone wrong and we’re ready to start working on milestone (N+1), then we definitely want to be at release N
> 
> So the creation of  —final happens sometime between those two points.
> 
> Here is an idea - maybe we do the creation of —final release N as the _first_ issue of milestone N+1
> 
> Then we only ever release dev releases to our cluster; and final releases are for public consumption.

Defining milestones and scope is not one of my strengths, so I'll be relying on others to help me figure out when we need a new release/milestone.

**Comment by dpb587** [comment]
I've deleted the `master` branch and have made `develop` the default.

I guess we'll just proceed from here, probably revisiting this discussion and @wdneto's points as we get further into automation and CI.
