### ISSUE TITLE
syslog_tls should not require configuration

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#63]
Currently it errors with the following if configuration properties are not provided...

```
Error 100: Error filling in template `syslog_tls.crt.erb' for `ingestor/0' (line 1: Can't find property `["logstash_ingestor.syslog_tls.ssl_cert"]')
Error 100: Error filling in template `syslog_to_redis.conf.erb' for `ingestor/0' (line 15: Can't find property `["logstash_ingestor.syslog_tls.port"]')
```

Instead, I believe the `syslog_tls` service should simply not run when the properties are empty.

**Comment by mrdavidlaing** [comment]
@dpb587,

>  the syslog_tls service should simply not run when the properties are empty.
> This is the correct behaviour.  Sorry about the bug.
