### ISSUE TITLE
Create final release 16

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#66]
As per https://github.com/logsearch/logsearch-boshrelease/issues/57#issuecomment-49169173, the first step of release 17 is to create a final release for 16.

**Comment by mrdavidlaing** [comment]
@dpb587, since we've resolved and deployed everything in release 16; and things seem to be running well, can you action this.

**Comment by dpb587** [comment]
Created [v16](https://github.com/logsearch/logsearch-boshrelease/releases/tag/v16).
