### ISSUE TITLE
Customizable logstash index format

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#68]
By default, logstash uses the index format of `logstash-%{+YYYY.MM.dd}`, creating a single index per day. However, I think there's a reasonable case for wanting to be able to configure it, depending on the installation requirements:
- for smaller or significantly larger logging requirements, it can be more efficient for both kibana usage and elasticsearch to use a different index date format (e.g. `logstash-%{+YYYY-ww}` for weekly)
- instead of using separate deployments, it can be more effective to segment indices by some property (e.g. `logstash-%{@environment}-%{+YYYY.MM.dd}` for environment-specific indices)

We could expose this as a `logstash_parser.index_format` property, defaulting to the current setting of `logstash-%{+YYYY.MM.dd}`.

**Comment by dpb587** [comment]
@mrdavidlaing, I don't think this is a requirement within the CI scope, so, if I sent a PR from personal time for this, would you consider it a worthwhile feature to merge?

**Comment by mrdavidlaing** [comment]
Of course.

I'm interested in your analysis of the circumstances when it makes sense to have different index segmentation.

In the CI use case, access to the last hour of data is more important than access to earlier data, so if changing the index segmentation can assist with that, then its perhaps a feature we can use there too.

**Comment by dpb587** [comment]
Resolved by #106.
