### ISSUE TITLE
Scope the auto-added tcp fields

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#69]
The `tcp` input automatically adds the following fields to all events:
- `host` - the host/port of the connecting client
- `sslsubject` - the SSL certificate subject of the connecting client when `ssl_verify` is enabled

I think those should automatically be renamed to `@ingestor.remote_host` and `@ingestor.sslsubject`, avoiding any confusion about whether an event's `host` field came from the ingestor or from whatever step(s) parsed out the message.

**Comment by mrdavidlaing** [comment]
agreed.
