### ISSUE TITLE
Remove logsearch-boshrelease < v12 

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#70]
I have de-activated the old `logsearch-boshrelease-public` AWS access keys to stop AWS complaining about their publication in a public repo.

This means that logsearch-boshrelease < v12 will no longer work.

I think we should remove these releases

**Comment by dpb587** [comment]
I'm not sure what you mean by remove them. If you mean delete the git tags, I'd disagree on git principles that tags generally live forever. Even still, it's not like we can actually, permanently delete the files/keys/commits from our git history, and, given the unlikelihood of someone even being interested in pulling an old version, I think it documents the project with a bit more history and background.

**Comment by mrdavidlaing** [comment]
The issue is that now that the S3 credentials published with <12 have been deactivated, those releases are "broken".

Consider:

```
/tmp$ git clone https://github.com/logsearch/logsearch-boshrelease
Cloning into 'logsearch-boshrelease'...
remote: Counting objects: 1791, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 1791 (delta 25), reused 0 (delta 0)
Receiving objects: 100% (1791/1791), 4.75 MiB | 204.00 KiB/s, done.
Resolving deltas: 100% (874/874), done.
Checking connectivity... done.
/tmp$ cd logsearch-boshrelease/
logsearch-boshrelease (develop) /tmp/logsearch-boshrelease$ git checkout v10

HEAD is now at d1422a2... release 10
logsearch-boshrelease ((detached) /tmp/logsearch-boshrelease$ bosh releases

+-----------+-----------+-------------+
| Name      | Versions  | Commit Hash |
+-----------+-----------+-------------+
| logsearch | 15.6-dev  | 3594505a+   |
|           | 15.7-dev* | 3594505a+   |
+-----------+-----------+-------------+
(*) Currently deployed
(+) Uncommitted changes

Releases total: 1

logsearch-boshrelease ((detached) /tmp/logsearch-boshrelease$ bosh upload release releases/logsearch-10.yml 

Copying packages
----------------
collectd (e50d8adf5e82798951cbcb638f41f8131e63bd5b) FOUND REMOTE
Downloading 59a26526-308b-4425-b1f6-fe5b16d5c00a...
Blobstore error: Failed to find object '59a26526-308b-4425-b1f6-fe5b16d5c00a', S3 response error: The AWS Access Key Id you provided does not exist in our records.
```

then

```
$ git checkout develop
Previous HEAD position was d1422a2... release 10
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
logsearch-boshrelease (develop) /tmp/logsearch-boshrelease$ bosh upload release releases/logsearch-10.yml 

Copying packages
----------------
collectd (e50d8adf5e82798951cbcb638f41f8131e63bd5b) MISSING
Cannot find object with given checksum
```

I'm not really sure whether its better to leave "broken" history, or re-write history.

@wdneto - do you have any thoughts / recommendations on this?

**Comment by dpb587** [comment]
I realize they're broken now, but I think we should just move forward and leave them be. Not that it's a vote, but I would unapologetically veto the idea of rewriting history.

**Comment by mrdavidlaing** [comment]
We could also leave the git history alone; but delete the files `/releases/logsearch-{1-12}.yml` going forward.

**Comment by aristotelesneto** [comment]
Removing the final releases seem like the only reasonable solution.

**Comment by aristotelesneto** [comment]
I'd also remove tags <v13, to make it 'harder' for people to choose those versions.

**Comment by dpb587** [comment]
I've removed releases and tags ≤12.
