### ISSUE TITLE
Rework queue job to be based on Kafka

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#73]
The Logsearch data pipeline currently looks like this:

```
shipper --> ingestor --> queue(redis) --> log_parser --> elasticsearch
```

The queue functions as:
1.  A buffer to prevent spikes in log volume from overloading the datastore
2.  A buffer to enable the datastore to go offline without loosing ingested data
3.  A source of pipeline throughput metrics

Currently the queue runs on a single node, so is a SPOF, and cannot be upgraded without downtime.

[Kafka](http://kafka.apache.org/) whose design goals more closely match the queue job's role.  

Specifically, it is:
- Distributed (by design)
- Designed to buffer several days worth of data, allowing multiple consumers to read data at a speed that suits them.  It's disk based (rather than memory based); and queues can be spread over many machines, so it can buffer a _lot_ more data.
- Fast (because it optimises for the fantastic sequential read performance of modern disks)

I propose that we switch the queue job to be based on Kafka, initially to remove the SPOF, but ultimately to enable our data pipeline to evolve to something like this:

```
shipper --> ingestor --> queue.raw* --> log_parser --> pubsub.decorated*
  --> pubsub.decorated* ----> queue.search* --> elasticsearch
                        |---> queue.longtermstorage* --> S3
                        |---> anomaly detection (reimann)  --> pubsub.notification* ---> elasticsearch
                        |---> anomaly detection (storm)  ---^                      |--> email

* - implemented with Kafka
```

**Comment by sopel** [comment]
:information_source: This details several preceding discussions we had around the subject of integrating [Apache Kafka](https://kafka.apache.org/), which might provide more details regarding the subject matter still accordingly:
- https://github.com/cityindex/logsearch/issues/273 - _Evaluate Apache Kafka_
- https://github.com/cityindex/logsearch/issues/269#issuecomment-30520629 - _Analyze/Implement Auto Scaling for managed queue (Redis)_
- https://github.com/cityindex/logsearch/issues/335 - _Evaluate migration to event sourcing for zero downtime blue green deployments_
- https://github.com/cityindex/logsearch/issues/321 - _Replace EC2 image/snapshot based with Elasticsearch snapshot based backup_

@mrdavidlaing - given I suggested to look into Kafka as the likely ideal solution for several of our long-term scaling and reliability issues, I'm more than happy to back this proposal now :)

**Comment by mrdavidlaing** [comment]
@sopel, Excellent; thanks for attaching references to earlier discussions

**Comment by mrdavidlaing** [comment]
After evaluating Kafka 0.8.1 for 2 weeks, we've decided that whilst the Kafka architecture is an ideal fit for LogSearch, the tooling, documentation and google juice isn't quite mature enough to make running it in production straight forward.

Accordingly, this effort will be put on hold, and re-evaluated in early 2015 once Kafka 0.9 / 1.0 is released

**Comment by dpb587** [comment]
Kafka would be cool and seems like it might be a great fit, but there are currently more interesting priorities for us to focus on. Since there are no active plans for us to work on this, nor is this issue causing us problems I'm going to close this.

**Comment by mrdavidlaing** [comment]
Re-opening since this topic keeps coming up.  We're not actively working on this; but it definately still seems like the correct thing to once fixing the queue makes it to the top of our backlog

**Comment by mrdavidlaing** [comment]
Due to the high operational overhead, we won't be including Kafka in this release
