### ISSUE TITLE
Collectd and ES as metrics collector and db

### ISSUE THREAD

**Issue by shinji62** [logsearch/logsearch-boshrelease#81]
Hi,

Logsearch package for CF is really good, I want to extend it.
So I am thinking about making collectd to be able to send to an collectd ingestor and by this way put metrics we need into Elastisearch (cpu, mem, network).

Do you think is reasonable ?

Thanks

**Comment by dpb587** [comment]
Hi - thanks for the comment. You may be interested in our [logsearch-shipper](https://github.com/logsearch/logsearch-shipper-boshrelease) release. It is intended to be installed on jobs and can forward both logs and metrics to a regular logsearch deployment. By default, it runs collectd and forwards cpu/mem/network/other host stats which you can view in Kibana ([example screenshot](https://github.com/logsearch/logsearch-shipper-boshrelease/pull/4#issuecomment-49830971)). We also use it to forward deployment-specific metrics, like logsearch performance stats ([example screenshot](https://github.com/logsearch/logsearch-shipper-boshrelease/pull/4#issuecomment-50299422)). More details are in the repo's readme.

Does this seem like what you are looking for?

**Comment by shinji62** [comment]
yes, the only things is you cannot separate collectd from the nxlog package.
It can be nice to make to different job and it's more flexible.

anyway thanks
