### ISSUE TITLE
Bug in filter_overrides

### ISSUE THREAD

**Issue by shinji62** [logsearch/logsearch-boshrelease#83]
I found a strange behavior, If you don't have any specific filter to override "[]" will be written in the final logstash.conf

So I made a small PR to put space instead.

**Comment by mrdavidlaing** [comment]
@shinji62 - Thanks for the PR!
Would you mind emailing a [signed CLA agreement](https://github.com/logsearch/licensing#signing-the-contributors-license-agreement) to me so we can merge it?

Thanks!

**Comment by shinji62** [comment]
Done.
thanks

**Comment by mrdavidlaing** [comment]
@shinji62 - perfect, thanks.  Welcome to the LogSearch contributors club!

@dpb587, Nothing "legal" standing in the way of this being merged.  Merge away when you're happy.
