### ISSUE TITLE
Drop collectd job and collectd/python package

### ISSUE THREAD

**Issue by dpb587** [logsearch/logsearch-boshrelease#86]
I propose we drop collectd (and python). We're not using it and it really has too limited of a use case to provide much value to anybody (e.g. it's only configurable to send metrics to librato because that's what we needed when we first started). It's also the only thing using the python package which we could then drop as well. I think the general community would be better served by a dedicated collectd boshrelease intended for colocation with more advanced configuration, or, in our case, we'll just continue [logsearch-shipper](https://github.com/logsearch/logsearch-shipper-boshrelease).

**Comment by dpb587** [comment]
@mrdavidlaing, any objections to doing this when looking for things to do?

**Comment by mrdavidlaing** [comment]
Agreed.  Goodbye collectd & python
