### ISSUE TITLE
bosh restart log_parser fails

### ISSUE THREAD

**Issue by mrdavidlaing** [logsearch/logsearch-boshrelease#90]
Attempting to bosh restart a log_parser node fails:

```
/labs-operations/meta$ bosh -n -d logsearch/deploy_manifest.yml restart log_parser 0

Performing `restart log_parser/0'...

Director task 1760
  Started preparing deployment
  Started preparing deployment > Binding deployment. Done (00:00:00)
  ...snip ...

  Started updating job log_parser > log_parser/0 (canary). Failed: `log_parser/0' is not running after update (00:05:35)

Error 400007: `log_parser/0' is not running after update

Task 1760 error

For a more detailed error report, run: bosh task 1760 --debug
```

SSHing into the node reveals that its the  `logsearch-logs`  or  `logsearch-metrics` job that has failed, eg:

```
$ monit summary
The Monit daemon 5.2.4 uptime: 7m 

Process 'log_parser'                running
Process 'log_parser-elasticsearch'  running
Process 'logsearch-logs'            running
Process 'logsearch-metrics'         not monitored
System 'system_21c3bd54-499a-4c07-838a-d3b8ea5c31c0' running
```

```
$  monit restart $FAILED_PROCESS
```

always seems to work

**Comment by mrdavidlaing** [comment]
My suspicion is that this is a startup race-condition.

However, I cannot replicate it with a `monit restart all`; only when doing a restart of the job via `bosh restart`

**Comment by dpb587** [comment]
This seems more likely to be a logsearch-shipper issue given it's the logsearch-metrics process.

**Comment by dpb587** [comment]
I've looked into this more and posted to the bosh mailing list about it - http://lists.cloudfoundry.org/pipermail/cf-bosh/2015-June/000182.html. I don't believe we're doing something inherently wrong here, so I'm going ahead and closing this, hoping for a better outcome or at least further insight from that thread.
